### ISSUE TITLE
The issue of install PGL/ogb_examples/nodeproppred/unimp/

### ISSUE THREAD

**Issue by severous** [PaddlePaddle/PGL#246]
当我尝试按照https://github.com/PaddlePaddle/PGL/tree/main/ogb_examples/nodeproppred/unimp
下的命令安装这个论文源码时，进行到这一步时
`pip install -e `
报错> -e option requires 1 argument
我将命令改变为`pip install -e  .`发生如下错误
>ERROR: Command errored out with exit status 1:
     command: /Users/zhangjinwei/anaconda3/envs/paddle/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/zhangjinwei/PycharmProjects/PGL/setup.py'"'"'; __file__='"'"'/Users/zhangjinwei/PycharmProjects/PGL/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sv/52s0q0dj4675hrng41bc3bqh0000gn/T/pip-pip-egg-info-edy3axn9
         cwd: /Users/zhangjinwei/PycharmProjects/PGL/
    Complete output (113 lines):
    ERROR: Exception:
    Traceback (most recent call last):
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
        crit = self.state.criteria[name]
    KeyError: 'numpy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
        yield
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
        data = self._fp.read(amt) if not fp_closed else b""
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
        data = self.__fp.read(amt)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/http/client.py", line 461, in read
        n = self.readinto(b)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/http/client.py", line 505, in readinto
        n = self.fp.readinto(b)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/socket.py", line 589, in readinto
        return self._sock.recv_into(b)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/ssl.py", line 1071, in recv_into
        return self.read(nbytes, buffer)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/ssl.py", line 929, in read
        return self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
        status = self.run(options, args)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
        return func(self, options, args)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/commands/wheel.py", line 159, in run
        reqs, check_supported_wheels=True
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
        requirements, max_rounds=try_to_avoid_resolution_too_deep,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
        name, crit = self._merge_into_criterion(r, parent=None)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
        crit = Criterion.from_requirement(self._p, requirement, parent)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
        if not cands:
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
        return bool(self._sequence)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
        return any(self)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 38, in _iter_built
        candidate = func()
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 169, in _make_candidate_from_link
        name=name, version=version,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
        version=version,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
        self.dist = self._prepare()
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
        dist = self._prepare_distribution()
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in _prepare_distribution
        self._ireq, parallel_builds=True,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
        return self._prepare_linked_requirement(req, parallel_builds)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in _prepare_linked_requirement
        self.download_dir, hashes,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 234, in unpack_url
        hashes=hashes,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 108, in get_http_url
        from_path, content_type = download(link, temp_dir.path)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/network/download.py", line 163, in __call__
        for chunk in chunks:
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 88, in response_chunks
        decode_content=False,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
        raise ReadTimeoutError(self._pool, None, "Read timed out.")
    pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.
    Traceback (most recent call last):
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/zhangjinwei/anaconda3/envs/paddle/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/sv/52s0q0dj4675hrng41bc3bqh0000gn/T/tmpemenvind', '--quiet', 'numpy>=1.16.4']' returned non-zero exit status 2.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/zhangjinwei/PycharmProjects/PGL/setup.py", line 126, in <module>
        'Programming Language :: Python :: 3.7',
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/dist.py", line 689, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/zhangjinwei/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/zhangjinwei/anaconda3/envs/paddle/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/sv/52s0q0dj4675hrng41bc3bqh0000gn/T/tmpemenvind', '--quiet', 'numpy>=1.16.4']' returned non-zero exit status 2.
    ----------------------------------------
WARNING: Discarding file:///Users/zhangjinwei/PycharmProjects/PGL. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
我的操作系统是MacOS python=3.7

**Comment by Yelrose** [comment]
你直接pip install pgl 对应的版本就好了，我们pip上面有mac的包

**Comment by Yelrose** [comment]
谢谢提醒，这个目录里面的requirement有点旧了，我们稍后更新一下。 pgl==1.2.1 paddle==1.8.5是那个论文的requirement，暂时只支持静态图模式。因为paddle 2.0全面动态图化了，这边的代码以后会迁移到动态图形式上去的。
