### ISSUE TITLE
mac os 环境运行报错

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/PGL#305]
欢迎您反馈PGL使用问题，非常感谢您对PGL的贡献！
在留下您的问题时，辛苦您同步提供如下信息：

#### 版本、环境信息
- PGL和PaddlePaddle版本号：
- paddlepaddle       2.1.2
- pgl                2.1.2

- 系统环境：
mac os

#### 复现信息：
运行node2vec的时候报错

Traceback (most recent call last):
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/site-packages/paddle/reader/decorator.py", line 342, in read_worker
    for d in r:
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/site-packages/pgl/utils/mp_reader.py", line 150, in pipe_reader
    p.start()
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/yanguangqing/opt/anaconda3/envs/representation_optimization/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'multiprocess_reader.<locals>._read_into_pipe'

**Comment by kirayummy** [comment]
将config.yaml里的sample_workers改成1可以跑通；
mac上的multiprocessing我们排查一下原因。

**Comment by Yelrose** [comment]
你好，python 3.8默认multiprocessing 使用spwan  可见这里 https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/
```
In Python 3.8 however, the default method to create a new process changed to spawn(), which has entirely different behavior. The child process now crashes because it cannot dereference the data we are asking it to:
```

可以这样修改一下代码，在train代码最开始加两行代码，把默认多进程改成使用fork。

```
import multiprocessing
multiprocessing.set_start_method('fork') 
```

后续，我们会对兼容性修复一下，感谢反馈

**Comment by natureLanguageQing** [comment]
非常感谢 我的mac是m1芯片的 很多工作都会报错。
