### ISSUE TITLE
No module named 'pgl.graph_kernel'

### ISSUE THREAD

**Issue by EmilyClimense** [PaddlePaddle/PGL#318]
#### 版本、环境信息
- PGL和PaddlePaddle版本号：PGL 2.1.5，PaddlePaddle2.1.2
- 系统环境： Windows10 python3.7
- 
#### 复现信息：
G:\Anaconda3\python.exe G:/PyCharm/var/py/PGL-main/ogb_examples/nodeproppred/unimp/main_arxiv.py
Traceback (most recent call last):
  File "G:/PyCharm/var/py/PGL-main/ogb_examples/nodeproppred/unimp/main_arxiv.py", line 7, in <module>
    from pgl.contrib.ogb.nodeproppred.dataset_pgl import PglNodePropPredDataset
  File "G:\PyCharm\var\py\PGL-main\pgl\__init__.py", line 20, in <module>
    from pgl import graph
  File "G:\PyCharm\var\py\PGL-main\pgl\graph.py", line 24, in <module>
    import pgl.graph_kernel as graph_kernel
ModuleNotFoundError: No module named 'pgl.graph_kernel'

**Comment by sys1874** [comment]
Since our unimp code was implemented by paddle1.8, please use the following command to install the appropriate environment:
``` 
pip install pgl==1.2.1
pip install paddlepaddle-gpu==1.8.5.post107 -f https://paddlepaddle.org.cn/whl/stable.html
```

**Comment by EmilyClimense** [comment]
> Since our unimp code was implemented by paddle1.8, please use the following command to install the appropriate environment:
> 
> ```
> pip install pgl==1.2.1
> pip install paddlepaddle-gpu==1.8.5.post107 -f https://paddlepaddle.org.cn/whl/stable.html
> ```



PGL and PADDLE have been reinstalled according to the suggested version, but errors are still reported

**Comment by EmilyClimense** [comment]
Dear developers：
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Very thanks for your reply!
&nbsp; &nbsp; &nbsp; &nbsp; the pgl&nbsp;and Paddle have been reinstalled according to the suggested version, but errors are still reported.
&nbsp; &nbsp; &nbsp; &nbsp; I'm really sorry to bother you again. I have tried many ways, but the problem is still not solved. If possible, could you please add my QQ 2541181491(月初白) to help me have a look? I really want to learn the method you studied.&nbsp;It doesn't matter if it's inconvenient.
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;




------------------ Original ------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Sep 7, 2021 5:01 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [PaddlePaddle/PGL] No module named 'pgl.graph_kernel' (#318)





 
Since our unimp code was implemented by paddle1.8, please use the following command to install the appropriate environment:
 pip install pgl==1.2.1 pip install paddlepaddle-gpu==1.8.5.post107 -f https://paddlepaddle.org.cn/whl/stable.html  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
