### ISSUE TITLE
pgl部分地方使用了接口fluid，在新版本paddlepaddle==2.6.1中被废弃了

### ISSUE THREAD

**Issue by dylan-yin** [PaddlePaddle/PGL#584]
>>> import pgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/pgl23/lib/python3.10/site-packages/pgl/__init__.py", line 27, in <module>
    from pgl import graph
  File "/root/anaconda3/envs/pgl23/lib/python3.10/site-packages/pgl/graph.py", line 28, in <module>
    from pgl.utils import op
  File "/root/anaconda3/envs/pgl23/lib/python3.10/site-packages/pgl/utils/op.py", line 21, in <module>
    from pgl.utils.helper import check_is_tensor
  File "/root/anaconda3/envs/pgl23/lib/python3.10/site-packages/pgl/utils/helper.py", line 18, in <module>
    from paddle.fluid.layers import core
ModuleNotFoundError: No module named 'paddle.fluid'

**Comment by Lyrnch** [comment]
我也遇到了这个问题i，请问你找到解决方法了吗

**Comment by zhaisilong** [comment]
I facing the same problem

**Comment by PlumBlossomMaid** [comment]
目前似乎最新版的PGL已经改过来了，从`paddle.framework`中`import core`。
