### ISSUE TITLE
erniesage的样例数据去哪下载？

### ISSUE THREAD

**Issue by Traeyee** [PaddlePaddle/PGL#69]
我按照[https://github.com/PaddlePaddle/PGL/tree/master/examples/erniesage](https://github.com/PaddlePaddle/PGL/tree/master/examples/erniesage)上去运行样例，然后报错：
```
+ python3 ./preprocessing/dump_graph.py -i ./data.txt -o ./workdir --encoding utf8 -l 40 --vocab_file ./vocab.txt
Traceback (most recent call last):
  File "./preprocessing/dump_graph.py", line 121, in <module>
    dump_graph(args)
  File "./preprocessing/dump_graph.py", line 57, in dump_graph
    with io.open(args.inpath, encoding=args.encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: './data.txt'
```
这应该是缺了样例数据吧，我翻了下文档也没找到，你们能提供吗？

**Comment by WeiyueSu** [comment]
刚刚补充了erniesage的样例数据，需要重新拉一下，另外ernie模型和词表需要另外在ernie页面下载的。
