### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by PengheLiu** [PaddlePaddle/PGL#83]
python2.7 
paddle1.7.1
pgl 1.1
在 k8s 队列和本地均会报这个错
+ python -m paddle.distributed.launch train.py --conf config/erniesage_v2_gpu.yaml
[INFO] 2020-05-25 19:28:03,309 [mp_reader.py:   23]:	ujson not install, fail back to use json instead
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    from dataset.graph_reader import GraphGenerator 
  File "/root/paddlejob/workspace/env_run/dataset/graph_reader.py", line 17, in <module>
    from dataset.base_dataset import BaseDataGenerator
  File "/root/paddlejob/workspace/env_run/dataset/base_dataset.py", line 31, in <module>
    from pgl.utils import mp_reader
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pgl/utils/mp_reader.py", line 28, in <module>
    from queue import Queue
ImportError: No module named queue

在本地可以修改为
from multiprocessing import Queue ，然后可以正常运行，但 k8s 队列上的机器我没有修改权限，请问如何解？

**Comment by edoardottt** [comment]
Maybe this can help
see on the top of the page. https://docs.python.org/2/library/queue.html

For Python2 it's Queue.
Try : 
`import Queue`

**Comment by PengheLiu** [comment]
@edoardottt 
thanks，I cannot modify the env files on the cluster, so I package the local environment to the cluster and it works.
